# Generated by Django 4.2.8 on 2024-03-28 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_alter_categories_id_alter_products_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Order placing date')),
                ('phone_number', models.CharField(max_length=20, verbose_name="Customer's phone")),
                ('needs_delivery', models.BooleanField(default=False, verbose_name='Needs delivery')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping address')),
                ('payment_by_card', models.BooleanField(default=False, verbose_name='Pay by card')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid already')),
                ('status', models.CharField(default='In process', max_length=50, verbose_name='Order status')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Item's title")),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Final price')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Quantity')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Order date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.products', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Ordered item',
                'verbose_name_plural': 'Ordered items',
                'db_table': 'ordered item',
            },
        ),
    ]
