# Generated by Django 4.2.8 on 2024-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_needs_delivery_order_delivery_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_process_paid', 'Paid'), ('in_process', 'In Process'), ('сompleted ', 'Completed'), ('cancelled', 'Cancelled')], default='in_process', max_length=50, verbose_name='Order status'),
        ),
    ]
